WARNING: AstropyDeprecationWarning: The private astropy._erfa module has been made into its own package, pyerfa, which is a dependency of astropy and can be imported directly using "import erfa" [astropy._erfa]
/u/kgrunthal/HD/HD_with_OS.py:342: FutureWarning: arrays to stack must be passed as a "sequence" type such as list or tuple. Support for non-sequence iterables such as generators is deprecated as of NumPy 1.16 and will raise an error in the future.
/usr/local/lib/python3.9/dist-packages/enterprise/signals/parameter.py:62: RuntimeWarning: divide by zero encountered in log
/usr/local/lib/python3.9/dist-packages/PTMCMCSampler/PTMCMCSampler.py:464: RuntimeWarning: All-NaN axis encountered
Traceback (most recent call last):
  File "/u/kgrunthal/HD/HD_with_OS.py", line 686, in <module>
    main()
  File "/u/kgrunthal/HD/HD_with_OS.py", line 621, in main
    _, _, _, OS_temp, OS_sig_temp = ostat.compute_os(params=setpars, psd='spectrum', fgw=f)
  File "/usr/local/lib/python3.9/dist-packages/enterprise_extensions/frequentist/optimal_statistic.py", line 122, in compute_os
    phiinvs = self.pta.get_phiinv(params, logdet=False)
  File "/usr/local/lib/python3.9/dist-packages/enterprise/signals/signal_base.py", line 410, in get_phiinv
    return self.get_phiinv_byfreq_cliques(params, logdet)
  File "/usr/local/lib/python3.9/dist-packages/enterprise/signals/signal_base.py", line 510, in get_phiinv_byfreq_cliques
    phi = self.get_phi(params, cliques=True)
  File "/usr/local/lib/python3.9/dist-packages/enterprise/signals/signal_base.py", line 618, in get_phi
    phis = [signalcollection.get_phi(params) for signalcollection in self._signalcollections]
  File "/usr/local/lib/python3.9/dist-packages/enterprise/signals/signal_base.py", line 618, in <listcomp>
    phis = [signalcollection.get_phi(params) for signalcollection in self._signalcollections]
  File "/usr/local/lib/python3.9/dist-packages/enterprise/signals/signal_base.py", line 959, in get_phi
    phi = phi.add(signal.get_phi(params), self._idx[signal])
  File "/usr/local/lib/python3.9/dist-packages/enterprise/signals/gp_signals.py", line 179, in get_phi
    self._phi = self._phi.set(phislc, slc)
  File "/usr/local/lib/python3.9/dist-packages/enterprise/signals/utils.py", line 261, in set
    self[idx] = other
ValueError: could not broadcast input array from shape (120,) into shape (40,)
